#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#
# Get function from functions library
#. /etc/init.d/functions
# Start the service
DATE=`date`

start() {
        echo "$DATE: starting fn_amoeba server" 
        nohup python app.py &
        PID=$(ps -af |grep app.py |grep -v grep |awk '{print $2;}')
        echo "Server PID: $PID"
        sleep 10
}
# Restart the service
stop(){ 
        echo "$DATE: stopping fn_amoeba server"
        PID=$(ps -af |grep app.py |grep -v grep |awk '{print $2;}')
	if [ "${#PID}" -gt "0" ] ; then
        echo "$DATE: Killing process $PID"
        kill $PID
        sleep 10
        else
        echo "$DATE: service is not running"
        fi 
}
# Check if app is running
status(){
        PID=$(ps -af |grep app.py |grep -v grep |awk '{print $2;}')
        echo $PID
        if [ "${#PID}" -gt "0" ] ;
        then echo "$DATE: service running, everything is fine"
        else echo "$DATE: service is not running"
        fi 
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status 
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
